# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rList <- function(m, niter) {
    .Call('_bamm_rList', PACKAGE = 'bamm', m, niter)
}

permute_matrix <- function(m, niter) {
    .Call('_bamm_permute_matrix', PACKAGE = 'bamm', m, niter)
}

permute_matrix_fb <- function(m, niter) {
    .Call('_bamm_permute_matrix_fb', PACKAGE = 'bamm', m, niter)
}

permute_matrix_indswap <- function(pam, niter) {
    .Call('_bamm_permute_matrix_indswap', PACKAGE = 'bamm', pam, niter)
}

null_dispersion_field_cat <- function(dfield, dfield_rand, lower_interval, upper_interval) {
    .Call('_bamm_null_dispersion_field_cat', PACKAGE = 'bamm', dfield, dfield_rand, lower_interval, upper_interval)
}

sdm_sim_rcpp <- function(A, M_orig, g0_input, suit_values, adj_list, nsteps, stochastic_dispersal, disp_prop2_suitability, disper_prop, progress_bar) {
    .Call('_bamm_sdm_sim_rcpp', PACKAGE = 'bamm', A, M_orig, g0_input, suit_values, adj_list, nsteps, stochastic_dispersal, disp_prop2_suitability, disper_prop, progress_bar)
}

